# Generated by Django 5.0.2 on 2024-03-06 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(db_index=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/images')),
                ('profile_slug', models.SlugField(default='', unique=True)),
                ('profile_info', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField(default=None, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not confirmed', 'Not confirmed')], db_index=True, max_length=100, null=True)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('otp', models.PositiveIntegerField(null=True)),
                ('otp_limit', models.IntegerField(null=True)),
                ('otp_delay', models.TimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('is_blocked', models.BooleanField(default=False, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('account_mode', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], db_index=True, default='Public', max_length=100)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('two_factor_auth_method', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Whatsapp SMS', 'Whatsapp SMS')], db_index=True, max_length=100, null=True)),
                ('password', models.CharField(db_index=True, default=None, max_length=200)),
                ('blockel_peoples', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('close_friends', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('mute_peoples', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
                ('Interest', models.ManyToManyField(blank=True, to='core_account.interest')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
