# Generated by Django 5.0.2 on 2024-07-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_id',
            field=models.CharField(db_index=True, default=None, max_length=50),
        ),
    ]
